// <auto-generated />
using System;
using GenesysForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenesysForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610174148_AddRulesets")]
    partial class AddRulesets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RuleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceVersionId");

                    b.HasIndex("RuleEntityId", "SourceVersionId", "Key")
                        .IsUnique();

                    b.ToTable("RuleDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            ContentJson = "{\"woundThresholdBonus\":2,\"strainThresholdBonus\":0,\"startingSkillKeys\":[\"resolve\",\"tactics\"]}",
                            Key = "starting-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            ContentJson = "{\"woundThresholdBonus\":0,\"strainThresholdBonus\":2,\"startingSkillKeys\":[\"resolve\"]}",
                            Key = "starting-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            ContentJson = "{\"characteristic\":\"willpower\",\"isCareerDefault\":false}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000006"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            ContentJson = "{\"characteristic\":\"intellect\",\"isCareerDefault\":false}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000007"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId", "EntityType", "Key")
                        .IsUnique();

                    b.ToTable("RuleEntities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Защитник, который держит строй и помогает группе пережить опасность.",
                            EntityType = "archetype",
                            Key = "guardian",
                            Name = "Страж",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Исследователь необычного, полагающийся на интуицию и внутреннюю дисциплину.",
                            EntityType = "archetype",
                            Key = "mystic",
                            Name = "Мистик",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Description = "Навык спокойствия, выдержки и сопротивления давлению.",
                            EntityType = "skill",
                            Key = "resolve",
                            Name = "Стойкость",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Description = "Навык планирования действий и чтения ситуации.",
                            EntityType = "skill",
                            Key = "tactics",
                            Name = "Тактика",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleSourceVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceBookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("SourceBookId", "Version")
                        .IsUnique();

                    b.ToTable("RuleSourceVersions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            SourceBookId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.Ruleset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("Rulesets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Открытый демо-набор для проверки rules-driven данных без защищенного контента.",
                            Name = "Демо-набор Genesys Forge",
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.SourceBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId", "Key")
                        .IsUnique();

                    b.ToTable("SourceBooks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Key = "demo-core",
                            Name = "Демо-правила",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleDefinition", b =>
                {
                    b.HasOne("GenesysForge.Domain.Rules.RuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Rules.RuleSourceVersion", null)
                        .WithMany()
                        .HasForeignKey("SourceVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleEntity", b =>
                {
                    b.HasOne("GenesysForge.Domain.Rules.Ruleset", null)
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleSourceVersion", b =>
                {
                    b.HasOne("GenesysForge.Domain.Rules.SourceBook", null)
                        .WithMany()
                        .HasForeignKey("SourceBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.SourceBook", b =>
                {
                    b.HasOne("GenesysForge.Domain.Rules.Ruleset", null)
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
