// <auto-generated />
using System;
using GenesysForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenesysForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611133210_ExpandDemoRuleCatalog")]
    partial class ExpandDemoRuleCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenesysForge.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("RulesetId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.CharacterSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCareerSkill")
                        .HasColumnType("boolean");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("RuleEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("XpSpent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RuleEntityId");

                    b.HasIndex("CharacterId", "RuleEntityId")
                        .IsUnique();

                    b.ToTable("CharacterSkills", (string)null);
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.CharacterSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("RulesetId");

                    b.ToTable("CharacterSnapshots", (string)null);
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.CharacterTalent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RuleEntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpCost")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RuleEntityId");

                    b.HasIndex("CharacterId", "RuleEntityId")
                        .IsUnique();

                    b.ToTable("CharacterTalents", (string)null);
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.XpLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("XpLedgerEntries", (string)null);
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RuleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceVersionId");

                    b.HasIndex("RuleEntityId", "SourceVersionId", "Key")
                        .IsUnique();

                    b.ToTable("RuleDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            ContentJson = "{\"characteristics\":{\"brawn\":3,\"agility\":2,\"intellect\":2,\"cunning\":2,\"willpower\":3,\"presence\":2},\"derivedStats\":{\"woundThreshold\":13,\"strainThreshold\":11,\"soak\":3,\"meleeDefense\":0,\"rangedDefense\":0}}",
                            Key = "starting-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            ContentJson = "{\"characteristics\":{\"brawn\":2,\"agility\":2,\"intellect\":3,\"cunning\":2,\"willpower\":3,\"presence\":2},\"derivedStats\":{\"woundThreshold\":10,\"strainThreshold\":13,\"soak\":2,\"meleeDefense\":0,\"rangedDefense\":0}}",
                            Key = "starting-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            ContentJson = "{\"careerSkillKeys\":[\"athletics\",\"resolve\",\"brawl\",\"melee\",\"ranged\",\"coercion\",\"leadership\",\"tactics\"],\"careerSkillRanksToAssign\":4}",
                            Key = "career-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-00000000000e"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            ContentJson = "{\"careerSkillKeys\":[\"education\",\"lore\",\"medicine\",\"mechanics\",\"perception\",\"negotiation\",\"leadership\",\"tactics\"],\"careerSkillRanksToAssign\":4}",
                            Key = "career-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-00000000000f"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            ContentJson = "{\"category\":\"general\",\"characteristic\":\"brawn\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000010"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000025"),
                            ContentJson = "{\"category\":\"general\",\"characteristic\":\"agility\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000011"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000026"),
                            ContentJson = "{\"category\":\"general\",\"characteristic\":\"willpower\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000012"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            ContentJson = "{\"category\":\"general\",\"characteristic\":\"willpower\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000006"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            ContentJson = "{\"category\":\"general\",\"characteristic\":\"intellect\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000007"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000027"),
                            ContentJson = "{\"category\":\"general\",\"characteristic\":\"intellect\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000013"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000028"),
                            ContentJson = "{\"category\":\"general\",\"characteristic\":\"intellect\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000014"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000029"),
                            ContentJson = "{\"category\":\"social\",\"characteristic\":\"presence\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000015"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002a"),
                            ContentJson = "{\"category\":\"social\",\"characteristic\":\"willpower\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000016"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002b"),
                            ContentJson = "{\"category\":\"social\",\"characteristic\":\"cunning\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000017"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002c"),
                            ContentJson = "{\"category\":\"social\",\"characteristic\":\"presence\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000018"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002d"),
                            ContentJson = "{\"category\":\"social\",\"characteristic\":\"presence\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000019"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002e"),
                            ContentJson = "{\"category\":\"combat\",\"characteristic\":\"brawn\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-00000000001a"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000002f"),
                            ContentJson = "{\"category\":\"combat\",\"characteristic\":\"brawn\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-00000000001b"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000030"),
                            ContentJson = "{\"category\":\"combat\",\"characteristic\":\"agility\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-00000000001c"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000031"),
                            ContentJson = "{\"category\":\"combat\",\"characteristic\":\"agility\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-00000000001d"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000032"),
                            ContentJson = "{\"category\":\"knowledge\",\"characteristic\":\"intellect\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-00000000001e"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000033"),
                            ContentJson = "{\"category\":\"knowledge\",\"characteristic\":\"intellect\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-00000000001f"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000034"),
                            ContentJson = "{\"category\":\"knowledge\",\"characteristic\":\"intellect\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000020"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000035"),
                            ContentJson = "{\"category\":\"knowledge\",\"characteristic\":\"intellect\",\"cost\":{\"type\":\"rank-table\",\"career\":{\"1\":5,\"2\":10,\"3\":15,\"4\":20,\"5\":25},\"nonCareer\":{\"1\":10,\"2\":15,\"3\":20,\"4\":25,\"5\":30}}}",
                            Key = "skill-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-000000000021"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            ContentJson = "{\"tier\":1,\"activation\":\"passive\",\"requirements\":[],\"cost\":{\"type\":\"fixed\",\"xp\":5}}",
                            Key = "talent-profile",
                            RuleEntityId = new Guid("10000000-0000-0000-0000-00000000000c"),
                            SourceVersionId = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId", "EntityType", "Key")
                        .IsUnique();

                    b.ToTable("RuleEntities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Защитник, который держит строй и помогает группе пережить опасность.",
                            EntityType = "archetype",
                            Key = "guardian",
                            Name = "Страж",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Исследователь необычного, полагающийся на интуицию и внутреннюю дисциплину.",
                            EntityType = "archetype",
                            Key = "mystic",
                            Name = "Мистик",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            Description = "Карьера бойца, который делает ставку на физическую подготовку и боевые навыки.",
                            EntityType = "career",
                            Key = "warrior",
                            Name = "Воин",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000f"),
                            Description = "Карьера исследователя, медика или наставника, который решает задачи знаниями.",
                            EntityType = "career",
                            Key = "scholar",
                            Name = "Ученый",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Description = "Общие физические действия: бег, прыжки, лазание и силовые испытания.",
                            EntityType = "skill",
                            Key = "athletics",
                            Name = "Атлетика",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Description = "Общие действия на точность, равновесие и ловкость.",
                            EntityType = "skill",
                            Key = "coordination",
                            Name = "Координация",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Description = "Общее наблюдение, поиск деталей и чтение окружения.",
                            EntityType = "skill",
                            Key = "perception",
                            Name = "Внимание",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Description = "Навык спокойствия, выдержки и сопротивления давлению.",
                            EntityType = "skill",
                            Key = "resolve",
                            Name = "Стойкость",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Description = "Навык планирования действий и чтения ситуации.",
                            EntityType = "skill",
                            Key = "tactics",
                            Name = "Тактика",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Description = "Обслуживание, ремонт и понимание устройств.",
                            EntityType = "skill",
                            Key = "mechanics",
                            Name = "Механика",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Description = "Первая помощь, лечение ран и знание тела.",
                            EntityType = "skill",
                            Key = "medicine",
                            Name = "Медицина",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Description = "Социальное влияние через симпатию, доверие и открытость.",
                            EntityType = "skill",
                            Key = "charm",
                            Name = "Обаяние",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Description = "Социальное давление через угрозы, страх и силу позиции.",
                            EntityType = "skill",
                            Key = "coercion",
                            Name = "Принуждение",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Description = "Социальная ложь, маскировка намерений и введение в заблуждение.",
                            EntityType = "skill",
                            Key = "deception",
                            Name = "Обман",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Description = "Социальное управление группой, вдохновение и командование.",
                            EntityType = "skill",
                            Key = "leadership",
                            Name = "Лидерство",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            Description = "Социальный торг, сделки и поиск взаимной выгоды.",
                            EntityType = "skill",
                            Key = "negotiation",
                            Name = "Переговоры",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001a"),
                            Description = "Бой без оружия и грубые физические столкновения.",
                            EntityType = "skill",
                            Key = "brawl",
                            Name = "Драка",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001b"),
                            Description = "Ближний бой с оружием.",
                            EntityType = "skill",
                            Key = "melee",
                            Name = "Холодное оружие",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001c"),
                            Description = "Дистанционные атаки легким оружием.",
                            EntityType = "skill",
                            Key = "ranged",
                            Name = "Стрельба",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001d"),
                            Description = "Дистанционные атаки тяжелым или громоздким оружием.",
                            EntityType = "skill",
                            Key = "heavy-ranged",
                            Name = "Тяжелое оружие",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001e"),
                            Description = "Знания академического, исторического и технического характера.",
                            EntityType = "skill",
                            Key = "education",
                            Name = "Образование",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000001f"),
                            Description = "Знания о легендах, традициях и необычных явлениях.",
                            EntityType = "skill",
                            Key = "lore",
                            Name = "Лор",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            Description = "Знания о дикой местности, существах и природных угрозах.",
                            EntityType = "skill",
                            Key = "nature",
                            Name = "Природа",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            Description = "Знания о тайных практиках, опасных теориях и скрытых культах.",
                            EntityType = "skill",
                            Key = "forbidden-knowledge",
                            Name = "Запретные знания",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            Description = "Демо-талант с фиксированной стоимостью для проверки покупки талантов.",
                            EntityType = "talent",
                            Key = "steady-stance",
                            Name = "Устойчивая стойка",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleSourceVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceBookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("SourceBookId", "Version")
                        .IsUnique();

                    b.ToTable("RuleSourceVersions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            SourceBookId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.Ruleset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("Rulesets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Открытый демо-набор для проверки rules-driven данных без защищенного контента.",
                            Name = "Демо-набор Genesys Forge",
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.SourceBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId", "Key")
                        .IsUnique();

                    b.ToTable("SourceBooks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Key = "demo-core",
                            Name = "Демо-правила",
                            RulesetId = new Guid("10000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GenesysForge.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.Character", b =>
                {
                    b.HasOne("GenesysForge.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Rules.Ruleset", null)
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.CharacterSkill", b =>
                {
                    b.HasOne("GenesysForge.Domain.Characters.Character", null)
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Rules.RuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.CharacterSnapshot", b =>
                {
                    b.HasOne("GenesysForge.Domain.Characters.Character", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Rules.Ruleset", null)
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.CharacterTalent", b =>
                {
                    b.HasOne("GenesysForge.Domain.Characters.Character", null)
                        .WithMany("Talents")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Rules.RuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.XpLedgerEntry", b =>
                {
                    b.HasOne("GenesysForge.Domain.Characters.Character", null)
                        .WithMany("XpLedgerEntries")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleDefinition", b =>
                {
                    b.HasOne("GenesysForge.Domain.Rules.RuleEntity", null)
                        .WithMany()
                        .HasForeignKey("RuleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenesysForge.Domain.Rules.RuleSourceVersion", null)
                        .WithMany()
                        .HasForeignKey("SourceVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleEntity", b =>
                {
                    b.HasOne("GenesysForge.Domain.Rules.Ruleset", null)
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.RuleSourceVersion", b =>
                {
                    b.HasOne("GenesysForge.Domain.Rules.SourceBook", null)
                        .WithMany()
                        .HasForeignKey("SourceBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Rules.SourceBook", b =>
                {
                    b.HasOne("GenesysForge.Domain.Rules.Ruleset", null)
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenesysForge.Domain.Characters.Character", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("Snapshots");

                    b.Navigation("Talents");

                    b.Navigation("XpLedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
